-- Spring Security用ユーザーテーブル
CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY(USERNAME)
);

-- Spring Security用権限テーブル
CREATE TABLE IF NOT EXISTS AUTHORITIES (
    USERNAME VARCHAR2(50) NOT NULL,
    AUTHORITY VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

-- ユーザー情報テーブル（プロフィール拡張）
CREATE TABLE IF NOT EXISTS APP_USERS (
    ID NUMBER(10) AUTO_INCREMENT,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    DISPLAY_NAME VARCHAR2(50) NOT NULL,
    BIO VARCHAR2(200),
    AVATAR_URL VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT APP_USERS_PK PRIMARY KEY(ID),
    CONSTRAINT FK_APP_USERS_USERNAME FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

-- 投稿テーブル（既存のUSER_COMMENTを置き換え）
CREATE TABLE IF NOT EXISTS POSTS (
    ID NUMBER(10) AUTO_INCREMENT,
    USER_ID NUMBER(10) NOT NULL,
    CONTENT VARCHAR2(400) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT POSTS_PK PRIMARY KEY(ID),
    CONSTRAINT POSTS_USER_FK FOREIGN KEY(USER_ID) REFERENCES APP_USERS(ID)
);

-- フォロー関係テーブル
CREATE TABLE IF NOT EXISTS FOLLOWS (
    ID NUMBER(10) AUTO_INCREMENT,
    FOLLOWER_ID NUMBER(10) NOT NULL,
    FOLLOWING_ID NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT FOLLOWS_PK PRIMARY KEY(ID),
    CONSTRAINT FOLLOWS_FOLLOWER_FK FOREIGN KEY(FOLLOWER_ID) REFERENCES APP_USERS(ID),
    CONSTRAINT FOLLOWS_FOLLOWING_FK FOREIGN KEY(FOLLOWING_ID) REFERENCES APP_USERS(ID),
    CONSTRAINT FOLLOWS_UNIQUE UNIQUE(FOLLOWER_ID, FOLLOWING_ID)
);

